### ISSUE TITLE
biblioteca python de acesso à API

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#1025]
```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/tno/issues/1043
- [ ] https://github.com/linea-it/tno/issues/1044
- [ ] https://github.com/linea-it/tno/issues/1045
```
