### ISSUE TITLE
Componente de mapas usando D3.js

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#1039]
- [x] Criar um componente que exibe os mapas
- [x] Criar a linhas da trajetória de predição para o mapa
- [x] Integrar as linhas com o mapa
- [x] Criar uma thumbnail do mapa para exibir na pagina inicial
```[tasklist]
### Tasks
- [x] Incluir o mapa no projeto tno
- [x] Reorganizar os demais itens da pagina de detalhes
```

**Comment by josiane-silwa** [comment]
Optamos por usar a biblioteca leaflet js

**Comment by josiane-silwa** [comment]
Essa branch está sendo continuada na branch 1078-componente-mapas-com-react-leaflet
