### ISSUE TITLE
Unique identifier for prediction events

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#1052]
Add a new field to the predictions table that is a unique identifier. This field will allow the creation of unique URLs for events, replacing the ids

```[tasklist]
### Tasks
- [x] The unique identifier must be a hash formed by joining three identifiers, the asteroid, the star and the time of the prediction.
- [ ] This hash should allow the event to be updated when the prediction is reprocessed.
- [ ] It is interesting to have a pair of fields to inform the event creation date and the last update date.
- [ ] Importing events should no longer delete pre-existing events, you should do a COPY ... On Conflict UPDATE using the new identifier.
```
