### ISSUE TITLE
Componente de mapas com react-leaflet

### ISSUE THREAD

**Issue by josiane-silwa** [linea-it/tno#1078]
```[tasklist]
### Tasks
- [x] Obter as linhas de incertezas do endpoint get_occultation_paths
- [x] Adicionar as linhas de incertezas no plot do mapa
- [x] Criação de thumbnail do mapa para o cardgrid da pagina de detalhes
- [x] Criação de thumbnail do mapa para o listgrid da pagina de detalhes
```
