### ISSUE TITLE
Passar os templates html da subscrição para templates django

### ISSUE THREAD

**Issue by josiane-silwa** [linea-it/tno#1088]
```[tasklist]
### Tasks
- [x] Criar template base
- [x] Criar template footer do email
- [x] Criar template header do email
- [x] Criar template body email ativação
- [x] Criar template body email welcome
- [x] Criar template body email confirmação
- [x] Criar template body email results_not_found
```

**Comment by josiane-silwa** [comment]
As tasks concluidas daqui foram passadas para a branch 1092
