### ISSUE TITLE
Geração de Mapas

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#700]
Melhorar a requisição dos mapas na lista para que a informação do mapa venha com o evento e não em requisição separada;

```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/tno/issues/713
- [ ] https://github.com/linea-it/tno/issues/714
- [ ] https://github.com/linea-it/tno/issues/716
```
