### ISSUE TITLE
Predict Occultation provenance

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#706]
Melhorar os dados de provenance de cada evento de predição, atualmente as informações estão sendo guardadas
em duas tabelas, a de predição e a de resultados do job de predição. 

O Ideal é que as informações de provenence estejam todas na mesma tabela da predição. 

- [x] Job Id ( Adicionar relação entre os eventos de predicao e o Job que os registrou )
- [x] Dynclass e Base Dynclass
- [x] Prediction Step (600, etc. passo utilizado em segundos)
- [x] Catalogo Gaia utilizado (Gaia DR2.. DR3...)
- [x] Bsp Source ( Origem do arquivo bsp utilizado)
- [x] Observation Source ( Origem dos dados de observações  AstDys, Mpc)
- [x] Orbital Elementents Source ( Origem dos parametros orbitais  AstDys, Mpc)
- [x] Ephemerides Planetaria (DE440 que foi utilizada)
- [x] Leap Second (Versão do NAIF)
- [x] Se rodou Nima ou não
- [x] Alterar a interface prediction job results para listar apenas os resultados referentes ao jobid. 

~~- [ ] BSP JPL Version~~ ( Ao inves de guardar a versao lembro que alguem tinha sugerido de guardar apenas a origem)
~~- [ ] GAIA Source ID~~ 

Entre outras coisas.
```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/tno/issues/683
- [ ] Inputs do MPC ou AstDys (incluindo dynamic class, diameter, semimajor axis, eccentricity, inclination, perihelion, aphelion)

```

**Comment by glaubervila** [comment]
@rcboufleur Sobre essa task Não ficou claro de onde virão esses valores, acredito que podemos transformar essa task em uma Issue e resolve-la no futuro. 

A tarefa como todo já está concluida, falta atualizar o ambiente com essas mudanças. 
@crisingulani  está trabalhando no ambiente também vou coordenar com ele disponibilizar essas modificações.
