### ISSUE TITLE
Backend: garantir a estratégia de geração e limpeza de mapas

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#714]
```[tasklist]
### Tasks
- [x] Alterar o endpoint para retornar as informações do mapa.
- [x] Rever estratégia de geração dos mapas.
- [x] ~Investigar possibilidade de~ gerar os mapas direto no container do portal
- [x] Garbage Collector para remover os mapas gerados
```
