### ISSUE TITLE
Predict Occultation highlights

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#718]
Criar um endpoint que retorne informações sobre os eventos de predições. 

```[tasklist]
### Tasks
- [x] Total de eventos de predição na tabela ( count(*) )
- [x] Data do envento mais antigo na tabela
- [x] Data do ultimo evento
- [x] Quantidade de asteroids com eventos
- [x] Total de eventos para  hoje
- [x] Quantidade de mapas gerados para os eventos de hoje.
- [x] Tamano em bytes de todos os mapas gerados para hoje.
- [x] Total de eventos na semana atual.
- [x] Total de eventos para a proxima semana.
- [x] Total de eventos no mes atual
- [x] Total de eventos no proximo mes
```

Exemplo do Json de retorno.
```
{
    "count": 79357,
    "earliest": "2023-08-01T03:00:20+00:00",
    "latest": "2024-06-29T02:43:36+00:00",
    "unique_asteroids": 2204,
    "today_count": 543,
    "today_already_have_map": 3,
    "total_maps_size": 176185,
    "week_count": 3786,
    "next_week_count": 3838,
    "month_count": 16362,
    "next_month_count": 16036
}
```
