### ISSUE TITLE
Filter Prediction Events

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#734]
Atualmente foi implementado uma função para cada tipo de filtro. 
O Ideal é que seja um unico endpoint que seja capaz de lidar com todas as clausulas possivels. 
Essa solução vai corrigir alguns problemas de lógica e facilitar a manutenção do principal endpoint da aplicação. 

```[tasklist]
### Tasks
- [x] Refatoração do endpoint Occultations
- [x] Endpoint Occultations Filtro por data
- [x] Endpoint Occultations Filtro por magnitude
- [x] Endpoint Occultations Filtro por asteroid name
- [x] Endpoint Occultations Filtro por asteroid dynamic class
- [ ] https://github.com/linea-it/tno/issues/727
- [x] Integrar a Função para calcular/armazenar o coeff path do evento
- [x] Função para verificar a visibilidade dada uma posição
- [x] Executar os calculos do coeff path em background (Celery
- [x] Remover autenticação provisoriamente por que estava impedindo o desenvolvimento no frontend
- [x] Criação de comandos no Django para executar as funções de coeff path e map manualmente
- [x] Remover lib material UI Icons 4 da lista dependencias por que estava demorando muito e causando falhas durante o build.
- [x] Atualizar algumas dependencias do Material 4 para o 5
- [x] Refatorar o componente de Filtros
- [x] Transformar a lista e o formulario de filtros em componentes, e atualizar as páginas dashboard/occultations e a home publica
- [x] Adicionar campos a tabela de ocultação para guardar informações do coeff_path
- [x] Adicionar indexes as principais colunas utilizadas no filtro
- [ ] https://github.com/linea-it/tno/issues/752
- [ ] https://github.com/linea-it/tno/issues/753
- [ ] https://github.com/linea-it/tno/issues/754
- [ ] https://github.com/linea-it/tno/pull/750
```

**Comment by gschwend** [comment]
@glaubervila  lembrete: adicionar lista de tasks

**Comment by glaubervila** [comment]
> @glaubervila lembrete: adicionar lista de tasks

Feito!
