### ISSUE TITLE
Concluir a implementação da autenticação do dashboard (parte privada do portal) iniciada pelo Matheus

### ISSUE THREAD

**Issue by gschwend** [linea-it/tno#749]
```[tasklist]
### Tasks
- [x] Separar (somente lógica no router) as páginas com acesso restrito.
- [x] Refactoring das funções de autenticação no frontend.
- [x] Após o login ou logout  redirecionar para página dashboard ao inves de home.
- [x] Corrigir bug ao recarregar a página, perde a sessão.
```
