### ISSUE TITLE
Verificar a integridade da interface após a integração do Slurm

### ISSUE THREAD

**Issue by rcboufleur** [linea-it/tno#757]
```[tasklist]
### Tasks
- [x] Verificar se todos os campos estão funcionando
- [x] Testar a execução com o banco de dados vazio
- [x] Fix erro ao submeter um novo job de predição, a tela fica em branco após clicar em submeter.
- [x] Correção da rota para págian detalhe da predição.
- [x] Diminuir o intervalo de update da barra de progresso para predict occultation.
- [ ] https://github.com/linea-it/tno/issues/766
```
