### ISSUE TITLE
Update Aladin version

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#761]
Instalar a nova versão do Aladin. para ser usado na página de detalhes de um evento de predição. 

```[tasklist]
### Tasks
- [x] Criar componente React para aladin
- [x] Criar metodo para centralizar  a imagem na posição da estrela
- [x] Adicionar o Componente na página do evento.
```
