### ISSUE TITLE
Prediction pipeline in the development environment

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#771]
```[tasklist]
### Tasks
- [x] Trazer os códigos do pipeline de predição (Repositório tno_pipeline)
- [x] Alterar o docker-compose local para executar o novo container
- [x] Atualizar a documentação do processo de instalação ambiente dev.
```
