### ISSUE TITLE
Asteroid Table

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#787]
É necessário alterar a forma como a tabela de asteroids é criada e atualizada. 

```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/tno/issues/786
- [ ] https://github.com/linea-it/tno/issues/788
- [ ] https://github.com/linea-it/tno/issues/790
- [ ] https://github.com/linea-it/tno/issues/791
- [ ] https://github.com/linea-it/tno/issues/794
- [ ] https://github.com/linea-it/tno/issues/798
- [ ] https://github.com/linea-it/tno/issues/799
- [ ] https://github.com/linea-it/tno/issues/801
- [ ] https://github.com/linea-it/tno/issues/802
- [ ] https://github.com/linea-it/tno/issues/803
- [ ] https://github.com/linea-it/tno/issues/804
- [ ] https://github.com/linea-it/tno/issues/806
- [ ] https://github.com/linea-it/tno/issues/807
- [x] Atualizar documentação de instalação do ambiente para utilizar o novo comando
- [x] Adicionar progress bar aos downloads
- [x] Corrigir erro com asteroid duplicado.
```
