### ISSUE TITLE
Replicar as novas informações do asteroid na tabela de predição

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#807]
```[tasklist]
### Tasks
- [x] Adicionar novos campos a tabela de predição
- [x] Corrigir o pipeline apos as alterações na tabela.
- [ ] Incluir no pipeline os dados da tabela asteroid.
- [ ] Registrar as predições com os dados do asteroid.
```
