### ISSUE TITLE
Pipeline de Predição rodando em Python 3.8

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#811]
Atualmente o pipeline de predição está rodando com codigos em python 2.x e outros em python 3.8 
Isso aumenta a complexidade e dificulta a manutenção. 
Acredito que alterar a parte 2.x para 3.8 seja simples de ser feito. 

```[tasklist]
### Tasks
- [x] Atualizar os códigos do pipeline para 2.x
- [x] Alterar a imagem docker
- [x] Separar o pipeline Orbit Trace em um novo diretório. Futuramente terá sua propria imagem.
- [x] Diminuir a quantidade de variaveis de ambiente
- [x] Remover códigos do pipeline Orbit Trace
- [x] Reorganizar a estrutura dos diretórios
```

```[tasklist]
### Tasks
```
