### ISSUE TITLE
alterar a interface de detalhes da predição

### ISSUE THREAD

**Issue by gschwend** [linea-it/tno#814]
```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/tno/issues/827
- [ ] adicionar os campos novos
- [ ] classificar os campos novos
```
