### ISSUE TITLE
Fix environment variables for production

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#848]
Necessário uma organização das variaveis de ambiente que são necessárias para utilização do Cluster. 

Ao fazer o deploy em tno-dev, foi necessário alterar varias configurações manualmente, processo demorado e dificil de identificar o que era necessário. 

```[tasklist]
### Tasks
- [ ] Mapear as variaveis necessárias em produção. 
- [ ] Script para verificar se todas as variaveis foram preenchidas corretamente. 
- [ ] Definir valores default para os ambientes. 
```
