### ISSUE TITLE
Public HOME page layout for different devices

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#860]
Atualmente a página publica esta com diversos problemas de exibição em diferentes tamanhos de tela. 
Objetivo é melhorar a apresentação e permitir o uso em dispositivos menores como notebooks, tablets e celulares. 

Esta tarefa pode ser quebrada em varios componentes. 

```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/tno/issues/861
- [ ] https://github.com/linea-it/tno/issues/862
- [ ] https://github.com/linea-it/tno/issues/863
- [ ] https://github.com/linea-it/tno/issues/864
- [ ] https://github.com/linea-it/tno/issues/858
- [ ] https://github.com/linea-it/tno/issues/867
```
