### ISSUE TITLE
Production Enviroment

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#888]
```[tasklist]
### Tasks
- [x] Corrigir problema na criação das tabelas relacionadas ao DES.
- [x] Recriar os arquivos de migração do banco de dados. Remover as migrações antigas.
- [x] Corrigir problema com permissão de usarios ao iniciar o container passando o UID e GID, demais grupos não funcionavam
- [x] Verificar se o miniconda está instalado no ambiente
- [x] Verificar se o enviroment python3 está disponivel no ambiente
- [x] Atualizar o ambinete python do cluster, antes de executar o pipeline.
- [x] Remover arquivos/documentações antigas ou que não são mais usadas
- [x] Separar variaveis de ambiente sensiveis. ex: Senhas
- [x] Documentar processo de deploy
- [ ] Criar versão/tag para o ambiente de produção
```
