### ISSUE TITLE
Deploy new Testing/Dev environment in srvnode06

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#901]
```[tasklist]
### Tasks
- [x] Criar arquivos de template para deploy
- [x] Workaround para updata_asteroid_table .
- [x] Documentação do deploy do ambiente
- [x] Validação do novo ambiente
- [x] Remover diretório antigo de dev da srvnode04
```
