### ISSUE TITLE
Subscription Fase 1 ( junto com lançamento )

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#930]
Permitir o registro dos emails de subscrição, no primeiro momento só coletar os emails dos interessados.  se possivel implementar esta fase antes do release. 

Objetivos nesta primeira fase.
- Ter o campo de subscrição na página publica.
- Criar o endpoint para registrar os email.
- Enviar email de boas vindas. (Opcional neste momento)

```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/tno/issues/931
- [ ] https://github.com/linea-it/tno/issues/921
- [ ] https://github.com/linea-it/tno/issues/933
- [ ] https://github.com/linea-it/tno/issues/946
- [ ] https://github.com/linea-it/tno/issues/947
- [ ] https://github.com/linea-it/tno/issues/941
- [ ] https://github.com/linea-it/tno/issues/945
- [x] Fluxo Unsubscribe
- [x] Tratar permissão no endpoint de subscrição
- [x] Página de confirmação de ativação da subscricao
- [x] Página de confirmação de unsubscribe
- [x] Template/Email de confirmação de unsubscribe
- [x] Textos para email de ativação e descadastro, fazer revisão dos textos com Rodrigo.
```

**Comment by glaubervila** [comment]
Fechada na #934
