### ISSUE TITLE
Subscription Fase 2 (Após lançamento)

### ISSUE THREAD

**Issue by glaubervila** [linea-it/tno#934]
```[tasklist]
### Tasks
- [x] Criar o endpoint para salvar as preferenças do filtro
- [x] Criar acesso na api service do frontend
- [x] Criar exibição do formulario pra o usuário
- [x] Criar a função que eviará os parametros para a api serevice
- [x] Tratamento dos dados antes de enviar para o banco de dados
- [x] Formatação do layout do formulario de preenchimento
- [x] Formatação do layout do formulario de exibição para usuario
- [x] Incluir magnitude max e min
- [x] Incluir magnitude drop min e max
- [x] Incluir campo de altitude no fomulario
- [x] Incluir link de acesso ao formulario na pagina enviada por email
- [x] Alterar a Exibicao dos resultados em tabelas ou grade
- [x] Botao de excluir
- [x] Botao de editar (leva pra o filtro de preenchimento com as opçoes antigas)
- [x] botao para editar o email
- [x] Colocar valores min e max n mesma coluna *** Nao ficou bom
- [x] Tirar geolocation e search location
- [x] Função para alterar o email
- [x] Retirar o botao de desabilitar my location
```

**Comment by gschwend** [comment]
TBD: criar task list ou subdividir em issues menores
